In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub

# Load Data From Kaggle
https://www.kaggle.com/datasets/datascikhan/e-commerce-customer-segmentation-2026

In [4]:
from pathlib import Path

path = kagglehub.dataset_download(
    "datascikhan/e-commerce-customer-segmentation-2026"
)
print("Path to dataset files:", path)

data_dir = Path(path)
csv_files = list(data_dir.rglob("*.csv"))

if not csv_files:
    raise FileNotFoundError(f"No CSV files found in {data_dir}")

df = pd.read_csv(csv_files[0])

Path to dataset files: /Users/yezawmyint/.cache/kagglehub/datasets/datascikhan/e-commerce-customer-segmentation-2026/versions/1

# Understanding data

In [5]:
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

column_info = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.astype(str).values
})

column_info

Rows: 50,000
Columns: 53

                      Column Name Data Type
0                     customer_id       str
1                customer_segment       str
2                segment_category       str
3                             age     int64
4                       age_group       str
5                          gender       str
6                         country       str
7                            city       str
8                  income_bracket       str
9                 education_level       str
10                employment_type       str
11                 marital_status       str
12                  tenure_months     int64
13                total_purchases     int64
14            avg_order_value_usd   float64
15                total_spent_usd   float64
16             purchase_frequency       str
17       days_since_last_purchase     int64
18           preferred_category_1       str
19           preferred_category_2       str
20           preferred_category_3       str
21               shopping_channel       str
22                    device_used       str
23                 payment_method       str
24                   return_count     int64
25                complaint_count     int64
26             satisfaction_score     int64
27             satisfaction_level       str
28                   loyalty_tier       str
29                email_open_rate   float64
30             click_through_rate   float64
31                conversion_rate   float64
32          social_media_presence       str
33    customer_lifetime_value_usd   float64
34  customer_acquisition_cost_usd   float64
35     customer_profitability_usd   float64
36                  recency_score     int64
37                frequency_score     int64
38                 monetary_score     int64
39                      rfm_score     int64
40               churn_risk_score     int64
41          customer_health_score     int64
42                   dataset_year     int64
43        customer_value_category       str
44                activity_status       str
45                  health_status       str
46            churn_risk_category       str
47                   rfm_category       str
48         profitability_category       str
49               engagement_level       str
50               behavior_segment       str
51              device_preference       str
52                   clv_category       str

## Check Data Validation

In [6]:
# Check Null
df.isnull().sum()

customer_id                          0
customer_segment                     0
segment_category                     0
age                                  0
age_group                            0
gender                               0
country                              0
city                                 0
income_bracket                       0
education_level                      0
employment_type                      0
marital_status                       0
tenure_months                        0
total_purchases                      0
avg_order_value_usd                  0
total_spent_usd                      0
purchase_frequency                   0
days_since_last_purchase             0
preferred_category_1                 0
preferred_category_2             16743
preferred_category_3             33257
shopping_channel                     0
device_used                          0
payment_method                       0
return_count                         0
complaint_count                      0
satisfaction_score                   0
satisfaction_level                   0
loyalty_tier                      1272
email_open_rate                      0
click_through_rate                   0
conversion_rate                      0
social_media_presence            12420
customer_lifetime_value_usd          0
customer_acquisition_cost_usd        0
customer_profitability_usd           0
recency_score                        0
frequency_score                      0
monetary_score                       0
rfm_score                            0
churn_risk_score                     0
customer_health_score                0
dataset_year                         0
customer_value_category              0
activity_status                      0
health_status                        0
churn_risk_category                  0
rfm_category                         0
profitability_category               0
engagement_level                     0
behavior_segment                     0
device_preference                    0
clv_category                         0
dtype: int64

In [7]:
# What kind of NULL are they
df[df.isnull().any(axis=1)]

,customer_id,customer_segment,segment_category,age,age_group,gender,country,city,income_bracket,education_level,...,customer_value_category,activity_status,health_status,churn_risk_category,rfm_category,profitability_category,engagement_level,behavior_segment,device_preference,clv_category
0,CUST-000001,Consumer,High Value Inactive,70,65+,Male,Canada,Winnipeg,150K+,Professional,...,High,Dormant,Excellent,Low,Potential Loyalists,High Profit,Low,Regular Buyer,Multi-Device,High CLV
1,CUST-000002,Premium,High Value Inactive,53,45-54,Female,Germany,Essen,25K-50K,High School,...,Medium,Inactive,Excellent,Medium,At Risk,High Profit,Low,Occasional Buyer,Desktop-First,High CLV
2,CUST-000003,Consumer,High Value Inactive,82,65+,Male,Mexico,Puebla,75K-100K,Bachelors,...,Very High,Dormant,Excellent,Very Low,Champions,High Profit,Low,Regular Buyer,Multi-Device,High CLV
3,CUST-000004,Enterprise,High Value Active,18,18-24,Male,Singapore,Singapore,150K+,Masters,...,Very High,Active,Excellent,Very Low,Champions,High Profit,High,Frequent Buyer,Mobile-First,High CLV
5,CUST-000006,Consumer,High Value Active,41,35-44,Male,France,Toulouse,50K-75K,PhD,...,High,Active,Excellent,Very Low,Champions,High Profit,Low,Frequent Buyer,Multi-Device,High CLV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49991,CUST-049992,Small Business,Medium Value Inactive,25,25-34,Male,Mexico,Puebla,50K-75K,PhD,...,Low,Active,Excellent,Low,Potential Loyalists,High Profit,Medium,Occasional Buyer,Multi-Device,Medium CLV
49993,CUST-049994,Consumer,High Value Inactive,55,55-64,Male,France,Montpellier,0-25K,Masters,...,High,Inactive,Fair,High,Potential Loyalists,High Profit,High,Occasional Buyer,Mobile-First,High CLV
49995,CUST-049996,Small Business,Low Value,22,18-24,Female,United States,San Antonio,50K-75K,PhD,...,Very Low,Inactive,Fair,High,Need Attention,High Profit,Low,Occasional Buyer,Multi-Device,Low CLV
49996,CUST-049997,Small Business,High Value Inactive,24,18-24,Male,Brazil,Rio de Janeiro,25K-50K,PhD,...,Very High,Dormant,Excellent,Low,Champions,High Profit,Medium,Regular Buyer,Multi-Device,High CLV
49999,CUST-050000,Consumer,High Value Inactive,77,65+,Female,United Arab Emirates,Sharjah,75K-100K,Masters,...,Very High,Inactive,Excellent,Low,Loyal,High Profit,Low,Occasional Buyer,Desktop-First,High CLV

In [8]:
# Fill Null into N/A
df=df.fillna("N/A")

In [9]:
# Check Duplication
df.duplicated().sum()

np.int64(0)

In [10]:
# Summary
df.describe()

,age,tenure_months,total_purchases,avg_order_value_usd,total_spent_usd,days_since_last_purchase,return_count,complaint_count,satisfaction_score,email_open_rate,...,customer_lifetime_value_usd,customer_acquisition_cost_usd,customer_profitability_usd,recency_score,frequency_score,monetary_score,rfm_score,churn_risk_score,customer_health_score,dataset_year
count,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.0
mean,45.64802,59.748240,99.418460,505.366911,50266.546156,62.971240,9.511740,6.99380,3.007960,0.500319,...,57722.068910,102.453505,57619.615405,3.954040,4.122720,3.717700,11.794460,26.84122,86.674100,2026.0
std,18.36795,34.310128,57.780178,285.604037,44071.209164,93.281404,5.782592,4.32425,1.417976,0.289515,...,52437.283546,56.373987,52437.172654,1.478949,1.077573,1.358633,2.680507,19.20729,16.107113,0.0
min,18.00000,1.000000,0.000000,10.050000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,...,0.000000,5.010000,-199.870000,1.000000,1.000000,1.000000,3.000000,0.00000,30.000000,2026.0
25%,30.00000,30.000000,49.000000,259.067500,13893.577500,2.000000,4.000000,3.00000,2.000000,0.251000,...,15488.650000,53.820000,15372.800000,3.000000,3.000000,3.000000,10.000000,10.00000,75.000000,2026.0
50%,45.00000,60.000000,99.000000,504.790000,37541.625000,19.000000,10.000000,7.00000,3.000000,0.500000,...,42236.310000,102.320000,42129.690000,5.000000,4.000000,4.000000,12.000000,25.00000,95.000000,2026.0
75%,60.00000,90.000000,150.000000,752.702500,76811.242500,77.000000,15.000000,11.00000,4.000000,0.752000,...,86714.875000,151.260000,86608.330000,5.000000,5.000000,5.000000,14.000000,40.00000,100.000000,2026.0
max,84.00000,119.000000,199.000000,999.990000,198574.140000,365.000000,19.000000,14.00000,5.000000,1.000000,...,294634.150000,200.000000,294479.720000,5.000000,5.000000,5.000000,15.000000,100.00000,100.000000,2026.0

In [ ]:
# Top 5 rows
df.head()

,customer_id,customer_segment,segment_category,age,age_group,gender,country,city,income_bracket,education_level,...,customer_value_category,activity_status,health_status,churn_risk_category,rfm_category,profitability_category,engagement_level,behavior_segment,device_preference,clv_category
0,CUST-000001,Consumer,High Value Inactive,70,65+,Male,Canada,Winnipeg,150K+,Professional,...,High,Dormant,Excellent,Low,Potential Loyalists,High Profit,Low,Regular Buyer,Multi-Device,High CLV
1,CUST-000002,Premium,High Value Inactive,53,45-54,Female,Germany,Essen,25K-50K,High School,...,Medium,Inactive,Excellent,Medium,At Risk,High Profit,Low,Occasional Buyer,Desktop-First,High CLV
2,CUST-000003,Consumer,High Value Inactive,82,65+,Male,Mexico,Puebla,75K-100K,Bachelors,...,Very High,Dormant,Excellent,Very Low,Champions,High Profit,Low,Regular Buyer,Multi-Device,High CLV
3,CUST-000004,Enterprise,High Value Active,18,18-24,Male,Singapore,Singapore,150K+,Masters,...,Very High,Active,Excellent,Very Low,Champions,High Profit,High,Frequent Buyer,Mobile-First,High CLV
4,CUST-000005,Premium,High Value Active,64,55-64,Male,United Arab Emirates,Fujairah,150K+,PhD,...,Medium,Active,Fair,Medium,Loyal,High Profit,Medium,Occasional Buyer,Desktop-First,High CLV

In [ ]:
# Bottom 5 rows
df.tail()

,customer_id,customer_segment,segment_category,age,age_group,gender,country,city,income_bracket,education_level,...,customer_value_category,activity_status,health_status,churn_risk_category,rfm_category,profitability_category,engagement_level,behavior_segment,device_preference,clv_category
49995,CUST-049996,Small Business,Low Value,22,18-24,Female,United States,San Antonio,50K-75K,PhD,...,Very Low,Inactive,Fair,High,Need Attention,High Profit,Low,Occasional Buyer,Multi-Device,Low CLV
49996,CUST-049997,Small Business,High Value Inactive,24,18-24,Male,Brazil,Rio de Janeiro,25K-50K,PhD,...,Very High,Dormant,Excellent,Low,Champions,High Profit,Medium,Regular Buyer,Multi-Device,High CLV
49997,CUST-049998,Consumer,High Value Inactive,29,25-34,Female,France,Strasbourg,100K-150K,Bachelors,...,Very High,Dormant,Excellent,Very Low,Champions,High Profit,Low,Regular Buyer,Multi-Device,High CLV
49998,CUST-049999,Consumer,High Value Active,74,65+,Male,Italy,Catania,100K-150K,Bachelors,...,High,Active,Good,Low,Champions,High Profit,Low,Frequent Buyer,Multi-Device,High CLV
49999,CUST-050000,Consumer,High Value Inactive,77,65+,Female,United Arab Emirates,Sharjah,75K-100K,Masters,...,Very High,Inactive,Excellent,Low,Loyal,High Profit,Low,Occasional Buyer,Desktop-First,High CLV

# Exploratory Data Analysis EDA

In [12]:
def show_fig():
    plt.tight_layout()
    plt.show()

plot_no = 1

In [14]:
print("Number of Unique Customer",df[0].unique().count_value())

KeyError: 0